"""Verify interactive surprises, one-answer guidance, and reversible visual state."""
from playwright.sync_api import sync_playwright,expect
import sys
BASE=sys.argv[1] if len(sys.argv)>1 else 'http://localhost:4173/'
with sync_playwright() as p:
    browser=p.chromium.launch()
    c=browser.new_context(viewport={'width':390,'height':844},reduced_motion='reduce')
    page=c.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(BASE,wait_until='networkidle')
    paths=page.locator('.map-route,.map-land').evaluate_all('(items)=>items.map(el=>el.getAttribute("d"))')
    page.locator('[data-map-day="3"]').click()
    page.locator('#map-night-toggle').click()
    expect(page.locator('#map-night-toggle')).to_have_attribute('aria-pressed','true')
    assert page.locator('.map-night-sky').evaluate('e=>getComputedStyle(e).opacity')=='1'
    assert paths==page.locator('.map-route,.map-land').evaluate_all('(items)=>items.map(el=>el.getAttribute("d"))')
    expect(page.locator('.map-photo-stamp')).to_have_count(4)
    for day in (1,2,3):
        path_color=page.locator(f'[data-map-route="{day}"] .map-route').first.evaluate('el=>getComputedStyle(el).stroke')
        legend_color=page.locator(f'.map-legend>span:nth-child({day}) i').evaluate('el=>getComputedStyle(el).backgroundColor')
        assert path_color==legend_color,(path_color,legend_color)
    page.locator('#map-play').click();page.locator('#map-next').click();page.locator('#map-next').click()
    expect(page.locator('#map-play-status')).to_contain_text('福井駅に帰着')
    expect(page.locator('#stamp-count')).to_have_text('0 / 6')
    page.evaluate('dispatchEvent(new Event("beforeprint"))')
    expect(page.locator('#map-night-toggle')).to_have_attribute('aria-pressed','false')
    page.evaluate('dispatchEvent(new Event("afterprint"))')
    expect(page.locator('#map-night-toggle')).to_have_attribute('aria-pressed','true')
    # The current itinerary day is used as the help dialog's initial date.
    page.locator('#day-tab-2').click();page.locator('#field-help-open').click()
    expect(page.locator('#field-help')).to_be_visible()
    expect(page.locator('[data-help-day="2"]')).to_have_attribute('aria-pressed','true')
    expect(page.locator('#field-help-close')).to_be_focused()
    for width,height in [(320,568),(390,844),(768,900),(1440,1000)]:
        page.set_viewport_size({'width':width,'height':height})
        for day in (1,2,3):
            page.locator(f'[data-help-day="{day}"]').click()
            for scene in ['drive','pace','comfort']:
                page.locator(f'[data-help-scene="{scene}"]').click()
                expect(page.locator('.field-answer:visible')).to_have_count(1)
                panel=page.locator('.field-answer:visible')
                assert panel.get_attribute('data-answer-day')==str(day)
                assert panel.get_attribute('data-answer-scene')==scene
                assert page.locator('#field-help').evaluate('d=>d.scrollWidth<=d.clientWidth')
                assert not page.evaluate('document.documentElement.scrollWidth>innerWidth')
    page.locator('[data-help-day="3"]').click();page.locator('[data-help-scene="drive"]').click()
    expect(page.locator('.field-answer:visible .field-anchor')).to_contain_text('予約調整中')
    page.locator('.field-answer:visible .field-action').click()
    expect(page.locator('#field-help')).not_to_be_visible()
    expect(page.locator('#place-ruins details')).to_have_attribute('open','')
    page.locator('#field-help-open').click();page.keyboard.press('Escape')
    expect(page.locator('#field-help-open')).to_be_focused()
    page.locator('#pocket-discovery').click();page.locator('.day-panel:not([hidden]) .discovery-draw').click()
    expect(page.locator('.gacha-show:visible')).to_have_count(0)
    assert not page.evaluate('document.getAnimations().some(a=>a.playState==="running")')
    # First load offline still enables both additions, without external requests.
    page.evaluate('navigator.serviceWorker.ready');page.reload(wait_until='networkidle')
    for asset in ['wonder.css','wonder.js']:
        assert page.evaluate('(asset)=>caches.match(asset).then(Boolean)',asset)
    c.set_offline(True);page.reload(wait_until='networkidle')
    page.locator('#map-night-toggle').click()
    page.locator('#field-help-open').click();expect(page.locator('.field-answer:visible')).to_have_count(1)
    assert not errors,errors;c.close()
    # Normal motion has finite capsule effects, suppresses double draws and cancels cleanly.
    c=browser.new_context(viewport={'width':320,'height':568},reduced_motion='no-preference')
    page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(BASE,wait_until='networkidle')
    page.locator('#pocket-discovery').click()
    drawer=page.locator('#discovery-1');button=drawer.locator('.discovery-draw')
    button.click();expect(button).to_be_disabled()
    expect(drawer.locator('.gacha-show')).to_be_visible()
    # A queued button-focus correction must not scroll the capsule out of view.
    page.wait_for_timeout(210)
    assert drawer.locator('.gacha-ball').evaluate('el=>{const r=el.getBoundingClientRect();return r.top>=0 && r.bottom<document.querySelector(".mobile-nav").getBoundingClientRect().top}')
    result=drawer.locator('.discovery-card:not([hidden])').get_attribute('data-discovery-card')
    button.evaluate('el=>{el.click();el.click();el.click()}')
    assert result==drawer.locator('.discovery-card:not([hidden])').get_attribute('data-discovery-card')
    expect(button).to_be_enabled();expect(drawer.locator('.gacha-show')).to_be_hidden()
    expect(drawer.locator('.discovery-card:visible')).to_be_focused()
    expect(drawer.locator('.discovery-card:visible h4')).to_be_in_viewport()
    button.click();drawer.evaluate('el=>el.open=false')
    expect(button).to_be_enabled();expect(drawer.locator('.gacha-show')).to_be_hidden()
    drawer.locator('summary').click();expect(drawer.locator('.discovery-card:visible')).to_have_count(1)
    button.click();page.emulate_media(reduced_motion='reduce')
    expect(button).to_be_enabled();expect(drawer.locator('.gacha-show')).to_be_hidden()
    assert not errors,errors;c.close()
    # The rain-plan anchor and existing guide remain available with scripts disabled.
    c=browser.new_context(java_script_enabled=False,service_workers='block')
    page=c.new_page();page.goto(BASE)
    expect(page.locator('#field-help-open')).to_have_attribute('href','#rain-plan')
    expect(page.locator('#map-night-toggle')).to_be_hidden()
    page.locator('#discovery-1>summary').click()
    expect(page.locator('#discovery-1 .discovery-card:visible')).to_have_count(4)
    c.close();browser.close()
    print('PASS: night map preserves geometry/routes/stamps, matching legend, print restoration, 9 sourced single-answer help states at 320–1440px, focus/anchors, finite capsule effects/double-click lock/cancellation, reduced motion, offline and no-JS fallback; no runtime errors.')
